version: '3.0'

services:

  nginx:
    build:
      context: ./src
    ports:
      - 8000:80
    env_file:
      - ./docker/nginx/.env
    depends_on:
      - php
    command: nginx -g 'daemon off;'
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./src/.env:/var/www/html/.env
    networks:
      - frontend
      - backend

  php:
    build:
      context: .
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./src/.env:/var/www/html/.env
    networks:
      - backend

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    env_file:
      - ./docker/mysql/.env
    networks:
      - backend

  sandbox:
    build:
      context: ./docker/sandbox
    privileged: yes
    networks:
      - backend


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 1500:80
    env_file:
      - ./docker/phpmyadmin/.env
    environment:
      - PMA_HOST=mysql
    networks:
      - frontend
      - backend
  redis:
      image: "redis:alpine"
      ports:
      - "6379:6379"
      volumes:
      - ./docker/redis/data:/var/lib/redis
      env_file:
      - ./docker/redis/.env
      networks:
      - backend

networks:
  frontend:
  backend:
